[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "foresure-forecast"
version = "0.1.0"
requires-python = ">=3.11"

[project.scripts]
foresure-forecast = "foresure_forecast.cli:app"
